version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: lumen
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Backend (Lumen)
  backend:
    build: ./backend-lumen
    ports:
      - "8000:80"
    environment:
      DB_HOST: mysql
      DB_PASSWORD: secret
      REDIS_HOST: redis
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  # Frontend (React App)
  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - app-network

  # Node-Redis API
  node-api:
    build: ./node-redis-api
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  mysql-data: